Add hugepages

diff --git a/community/modules/internal/slurm-gcp/instance_template/files/startup_sh_unlinted b/community/modules/internal/slurm-gcp/instance_template/files/startup_sh_unlinted
--- a/community/modules/internal/slurm-gcp/instance_template/files/startup_sh_unlinted
+++ b/community/modules/internal/slurm-gcp/instance_template/files/startup_sh_unlinted
@@ -31,29 +31,29 @@ CURL="curl -sS --fail --header Metadata-Flavor:Google"
 PING_METADATA="ping -q -w1 -c1 $METADATA_SERVER"
 echo "INFO: $PING_METADATA"
 for i in $(seq 10); do
-    [ $i -gt 1 ] && sleep 5;
-    $PING_METADATA > /dev/null && s=0 && break || s=$?;
-    echo "ERROR: Failed to contact metadata server, will retry"
+	[ $i -gt 1 ] && sleep 5
+	$PING_METADATA >/dev/null && s=0 && break || s=$?
+	echo "ERROR: Failed to contact metadata server, will retry"
 done
 if [ $s -ne 0 ]; then
-    echo "ERROR: Unable to contact metadata server, aborting"
-    wall -n '*** Slurm setup failed in the startup script! see `journalctl -u google-startup-scripts` ***'
-    exit 1
+	echo "ERROR: Unable to contact metadata server, aborting"
+	wall -n '*** Slurm setup failed in the startup script! see `journalctl -u google-startup-scripts` ***'
+	exit 1
 else
-    echo "INFO: Successfully contacted metadata server"
+	echo "INFO: Successfully contacted metadata server"
 fi
 
 PING_GOOGLE="ping -q -w1 -c1 8.8.8.8"
 echo "INFO: $PING_GOOGLE"
 for i in $(seq 5); do
-    [ $i -gt 1 ] && sleep 2;
-    $PING_GOOGLE > /dev/null && s=0 && break || s=$?;
+	[ $i -gt 1 ] && sleep 2
+	$PING_GOOGLE >/dev/null && s=0 && break || s=$?
 	echo "failed to ping Google DNS, will retry"
 done
 if [ $s -ne 0 ]; then
-    echo "WARNING: No internet access detected"
+	echo "WARNING: No internet access detected"
 else
-    echo "INFO: Internet access detected"
+	echo "INFO: Internet access detected"
 fi
 
 mkdir -p $SCRIPTS_DIR
@@ -77,7 +77,6 @@ rm -rf "$SCRIPTS_ZIP"
 chown slurm:slurm -R "$SCRIPTS_DIR" || true
 chmod 700 -R "$SCRIPTS_DIR"
 
-
 if [ -f $FLAGFILE ]; then
 	echo "WARNING: Slurm was previously configured, quitting"
 	exit 0
@@ -86,7 +85,7 @@ touch $FLAGFILE
 
 function tpu_setup {
 	#allow the following command to fail, as this attribute does not exist for regular nodes
-	docker_image=$($CURL $URL/instance/attributes/slurm_docker_image 2> /dev/null || true)
+	docker_image=$($CURL $URL/instance/attributes/slurm_docker_image 2>/dev/null || true)
 	if [ -z $docker_image ]; then #Not a tpu node, do not do anything
 		return
 	fi
@@ -106,9 +105,14 @@ function tpu_setup {
 	worker_id=$($CURL $URL/instance/attributes/tpu-env | awk '/WORKER_ID/ {print $2}' | tr -d \')
 	real_name=$(parse_metadata $worker_id $input_string)
 
+	# enable transparent hugepages
+	# TPU runtime startup and shutdown time should be significantly improved on TPU v5e and newer.
+
+	echo always >/sys/kernel/mm/transparent_hugepage/enabled
+
 	#Prepare to docker pull with gcloud
 	mkdir -p /root/.docker
-	cat << EOF > /root/.docker/config.json
+	cat <<EOF >/root/.docker/config.json
 {
   "credHelpers": {
     "gcr.io": "gcloud",
@@ -125,7 +129,7 @@ EOF
 	if [ $CGV == 2 ]; then
 		CGROUP_FLAGS="--cgroup-parent=docker.slice --cgroupns=private --tmpfs /run --tmpfs /run/lock --tmpfs /tmp:exec,nosuid,mode=1777"
 		if [ ! -f /etc/systemd/system/docker.slice ]; then #In case that there is no slice prepared for hosting the containers create it
-			printf "[Unit]\nDescription=docker slice\nBefore=slices.target\n[Slice]\nCPUAccounting=true\nMemoryAccounting=true" > /etc/systemd/system/docker.slice
+			printf "[Unit]\nDescription=docker slice\nBefore=slices.target\n[Slice]\nCPUAccounting=true\nMemoryAccounting=true" >/etc/systemd/system/docker.slice
 			systemctl start docker.slice
 		fi
 	fi
@@ -136,8 +140,8 @@ EOF
 	# 	TPU_FLAGS="--privileged"
 	# fi
 
-  # pass the hostname into slurmd container, so the work distribution frameworks will be able to correctly
-  # identify local address and hostname and coordinate the work
+	# pass the hostname into slurmd container, so the work distribution frameworks will be able to correctly
+	# identify local address and hostname and coordinate the work
 	docker run -d $CGROUP_FLAGS $TPU_FLAGS --net=host --name=slurmd --hostname="$(hostname)" --entrypoint=/usr/bin/systemd --restart unless-stopped $docker_image
 	# wait until file is there
 	local slurmd_config_path="/etc/sysconfig/slurmd"
